### ISSUE TITLE
Exception in plugin IdeaVimExtension (1.6.6)

### ISSUE THREAD

**Issue by jssda** [hadix-lin/ideavim_extension#109]
IDE version: 2022.3.1 (ULtimate Edition)
添加了美式键盘: 
![image](https://user-images.githubusercontent.com/33473639/209092981-f7853f69-7388-4b44-b282-f746017eef29.png)

配置完
 `set keep-english-in-normal`
`set keep-english-in-normal-and-restore-in-insert`
两个选项之后, 重启 IDE 直接报错, 影响 IdeVim 也不可用

```
java.lang.NoSuchMethodError: 'void com.maddyhome.idea.vim.vimscript.services.OptionService.setOption$default(com.maddyhome.idea.vim.vimscript.services.OptionService, com.maddyhome.idea.vim.vimscript.services.OptionService$Scope, java.lang.String, java.lang.String, int, java.lang.Object)'
	at io.github.hadixlin.iss.KeepEnglishInNormalAndRestoreInInsertExtension.init(KeepEnglishInNormalAndRestoreInInsertExtension.kt:23)
	at com.maddyhome.idea.vim.extension.VimExtensionRegistrar.enableDelayedExtensions(VimExtensionRegistrar.kt:101)
	at com.maddyhome.idea.vim.VimPlugin.turnOnPlugin(VimPlugin.java:383)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:429)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by hadix-lin** [comment]
请更新插件到最新版本重试

https://github.com/hadix-lin/ideavim_extension/releases/tag/v1.6.7

**Comment by jssda** [comment]
更新了新版本  依旧报这个错

**Comment by hadix-lin** [comment]
IdeaVim
IdeaVimExtension

这两个插件安装的版本都发一下

理论上需要IdeaVim2.0 + IdeaVimExtension 1.6.7

**Comment by jssda** [comment]
感谢 已经解决   

IdeaVim 插件版本不对 也没有提示更新    去官方页面下载更新一下就好了
