### ISSUE TITLE
忽然发现报错

### ISSUE THREAD

**Issue by cdadar** [hadix-lin/ideavim_extension#31]
```
java.lang.IllegalThreadStateException: process hasn't exited
	at java.lang.UNIXProcess.exitValue(UNIXProcess.java:423)
	at io.github.hadixlin.iss.lin.LinFcitxRemoteSwitcher.execFcitxRemote(LinFcitxRemoteSwitcher.kt:19)
	at io.github.hadixlin.iss.lin.LinFcitxRemoteSwitcher.restore(LinFcitxRemoteSwitcher.kt:13)
	at io.github.hadixlin.iss.SystemInputMethodSwitcher.restore(SystemInputMethodSwitcher.kt:22)
	at io.github.hadixlin.iss.InputMethodAutoSwitcher$exitInsertModeListener$1$beforeCommandFinished$2.run(InputMethodAutoSwitcher.kt:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by hadix-lin** [comment]
我自己不使用Linux，这个插件的Linux支持是另外一位网友提供的。我自己没有方便的环境进行测试。

从这个异常栈来看，应该是个linux进程管理相关的问题。如果仅是偶尔出现，频率较低，不影响使用，那忽略它就好了。
如果频率较高，影响正常使用，请您帮忙进行测试，提供更明确的复现步骤，我会尝试重现并修复该问题。

**Comment by hadix-lin** [comment]
v1.3.9尝试修正了该问题，请下载试用。

https://github.com/hadix-lin/ideavim_extension/releases/download/v1.3.9/ideavim_extension.zip
