### ISSUE TITLE
update ideavim plugin cause this plugin crash

### ISSUE THREAD

**Issue by zyf0330** [hadix-lin/ideavim_extension#32]
ideavim version: 0.52
error stack
```
Plugin 'IdeaVimExtension' failed to initialize and will be disabled.  Please restart WebStorm.

java.lang.NoClassDefFoundError: com/maddyhome/idea/vim/option/Options
    at io.github.hadixlin.iss.InputMethodAutoSwitcherComponent$keepEnglishInNormalOption$2.invoke(InputMethodAutoSwitcherComponent.kt:10)
    at io.github.hadixlin.iss.InputMethodAutoSwitcherComponent$keepEnglishInNormalOption$2.invoke(InputMethodAutoSwitcherComponent.kt:7)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at io.github.hadixlin.iss.InputMethodAutoSwitcherComponent.getKeepEnglishInNormalOption(InputMethodAutoSwitcherComponent.kt)
    at io.github.hadixlin.iss.InputMethodAutoSwitcherComponent.initComponent(InputMethodAutoSwitcherComponent.kt:22)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:482)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:449)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:473)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:407)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:393)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
    at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:347)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.maddyhome.idea.vim.option.Options PluginClassLoader[IdeaVimExtension, 1.3.8] com.intellij.ide.plugins.cl.PluginClassLoader@7453df8
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:51)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 34 more

```

**Comment by remove** [comment]
更新后出现同样的错误

**Comment by hadix-lin** [comment]
今天IdeaVim稳定版升级到0.52了，有一个api变更了，所以导致IdeaVimExtension报错。
今晚我会解决这个问题并发布。

**Comment by hadix-lin** [comment]
v1.3.9修复该问题，请下载。

https://github.com/hadix-lin/ideavim_extension/releases/download/v1.3.9/ideavim_extension.zip
