### ISSUE TITLE
对0.53的 ideavim不兼容

### ISSUE THREAD

**Issue by mask-zpt** [hadix-lin/ideavim_extension#36]
```java
Plugin 'IdeaVimExtension' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

kotlin.TypeCastException: null cannot be cast to non-null type com.maddyhome.idea.vim.option.Option
    at io.github.hadixlin.iss.InputMethodAutoSwitcherComponent$Companion.getOption(InputMethodAutoSwitcherComponent.kt:45)
    at io.github.hadixlin.iss.InputMethodAutoSwitcherComponent$keepEnglishInNormalOption$2.invoke(InputMethodAutoSwitcherComponent.kt:10)
    at io.github.hadixlin.iss.InputMethodAutoSwitcherComponent$keepEnglishInNormalOption$2.invoke(InputMethodAutoSwitcherComponent.kt:7)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at io.github.hadixlin.iss.InputMethodAutoSwitcherComponent.getKeepEnglishInNormalOption(InputMethodAutoSwitcherComponent.kt)
    at io.github.hadixlin.iss.InputMethodAutoSwitcherComponent.initComponent(InputMethodAutoSwitcherComponent.kt:22)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:486)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:447)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:471)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:405)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:391)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
    at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:342)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by hadix-lin** [comment]
我试试重现一下看看

**Comment by hadix-lin** [comment]
@mask-zpt 我没能重现这个问题，请提供一下您使用的IdeaVimExtension版本，如果不是1.3.9请先升级到1.3.9，谢谢。

**Comment by NoDocCat** [comment]
@hadix-lin 
我之前用0.52的时候出现过这个问题, 然后更新到0.53就好了, 现在vim插件更新到0.54又出现这个问题了

**Comment by transtone** [comment]
ideavim-0.54 更新后无法使用。

**Comment by hadix-lin** [comment]
之前我一直尽力保持兼容旧版IDE，结果导致了对新版本的兼容越来越难做。

这两天我会更新一个版本，兼容策略保持跟IdeaVim本身一致。

**Comment by hbprotoss** [comment]
> 之前我一直尽力保持兼容旧版IDE，结果导致了对新版本的兼容越来越难做。
> 
> 这两天我会更新一个版本，兼容策略保持跟IdeaVim本身一致。

对某个版本之前的旧版兼容进入maintain状态得了，尽量兼容新版

**Comment by yangxuanx** [comment]
> 之前我一直尽力保持兼容旧版IDE，结果导致了对新版本的兼容越来越难做。
> 
> 两者天我会更新一个版本，兼容策略保持跟IdeaVim本身一致。

感谢您的付出，希望尽快使用上新版本

**Comment by hbprotoss** [comment]
master分支的版本测试没问题

**Comment by yangxuanx** [comment]
> master分支的版本测试没问题

linux下的fcitx无法在退出插入模式自动切换

**Comment by transtone** [comment]
编译了最新的 master 分支，不报错，但无效，回到 normal 模式不自动切换输入法。

系统 win10pro-64-1909

**Comment by hadix-lin** [comment]
新版本已经更新，插件中心需要等2工作日审核。

有需要的朋友可以在此自行[下载安装](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.4.0/ideavim_extension.zip)

**Comment by transtone** [comment]
> 新版本已经更新，插件中心需要等2工作日审核。
> 
> 有需要的朋友可以在此自行[下载安装](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.4.0/ideavim_extension.zip)

大侠，确定 win10 下能用吗？我下载后本地安装，还是和之前一样，不报错，也不生效。
对了，我测试的 webstorm。

**Comment by transtone** [comment]
`:set nokeep-english-in-normal-and-restore-in-insert 保留输入法自动切换功能，但是回到insert模式不恢复输入法`

设置这个选项之后，如果 insert 是中文，按 ESC 之后，不会自动切换成英文。

**Comment by yangxuanx** [comment]
测试了一下发布的新版本。Linux环境下不能切换

> 新版本已经更新，插件中心需要等2工作日审核。
> 
> 有需要的朋友可以在此自行[下载安装](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.4.0/ideavim_extension.zip)

刚刚测试了一下，Linux下不能自动切换

**Comment by hadix-lin** [comment]
> `:set nokeep-english-in-normal-and-restore-in-insert 保留输入法自动切换功能，但是回到insert模式不恢复输入法`
> 
> 设置这个选项，如果 insert 是中文，按 ESC 之后，不会自动切换成英文。

需要保证 :set keep-english-in-normal  这个存在

**Comment by transtone** [comment]
> > `:set nokeep-english-in-normal-and-restore-in-insert 保留输入法自动切换功能，但是回到insert模式不恢复输入法`
> > 设置这个选项，如果 insert 是中文，按 ESC 之后，不会自动切换成英文。
> 
> no开头的指令，是用来关闭功能的，需要事先有设置过其他的指令
> 需要保证 :set keep-english-in-normal[-and-restore-in-insert] 这个存在

我也曾想到这一点，但1.39这样设置是可以切换的，所以困惑了。

**Comment by hadix-lin** [comment]
> > > `:set nokeep-english-in-normal-and-restore-in-insert 保留输入法自动切换功能，但是回到insert模式不恢复输入法`
> > > 设置这个选项，如果 insert 是中文，按 ESC 之后，不会自动切换成英文。
> > 
> > 
> > no开头的指令，是用来关闭功能的，需要事先有设置过其他的指令
> > 需要保证 :set keep-english-in-normal[-and-restore-in-insert] 这个存在
> 
> 我也曾想到这一点，但1.3.9这样设置是可以切换的，所以困惑了。

这个逻辑我有改动过，到目前为止我也没有很确定到底哪种逻辑更合理，可以讨论一下。
