### ISSUE TITLE
Exception with ideavim 0.61

### ISSUE THREAD

**Issue by zyf0330** [hadix-lin/ideavim_extension#59]
java.lang.NoSuchMethodError: 'void com.maddyhome.idea.vim.extension.VimExtensionFacade.putKeyMapping(java.util.Set, java.util.List, java.util.List, boolean)'
	at io.github.hadixlin.iss.InputMethodAutoSwitcher.enable(InputMethodAutoSwitcher.kt:106)
	at io.github.hadixlin.iss.KeepEnglishInNormalExtension.init(KeepEnglishInNormalExtension.kt:16)
	at com.maddyhome.idea.vim.extension.VimExtensionRegistrar$registerExtension$1.valueChange(VimExtensionRegistrar.kt:67)
	at com.maddyhome.idea.vim.extension.VimExtensionRegistrar$registerExtension$1.valueChange(VimExtensionRegistrar.kt:31)
	at com.maddyhome.idea.vim.option.Option.fireOptionChangeEvent(Option.java:108)
	at com.maddyhome.idea.vim.option.ToggleOption.update(ToggleOption.java:80)
	at com.maddyhome.idea.vim.option.ToggleOption.set(ToggleOption.java:50)
	at com.maddyhome.idea.vim.option.OptionsManager.parseOptionLine(OptionsManager.kt:234)
	at com.maddyhome.idea.vim.ex.handler.SetHandler.parseOptionLine(SetHandler.kt:40)
	at com.maddyhome.idea.vim.ex.handler.SetHandler.execute(SetHandler.kt:36)
	at com.maddyhome.idea.vim.ex.vimscript.VimScriptParser.executeText(VimScriptParser.kt:113)
	at com.maddyhome.idea.vim.ex.vimscript.VimScriptParser.executeFile(VimScriptParser.kt:94)
	at com.maddyhome.idea.vim.VimPlugin.executeIdeaVimRc(VimPlugin.java:250)
	at com.maddyhome.idea.vim.VimPlugin.registerIdeavimrc(VimPlugin.java:242)
	at com.maddyhome.idea.vim.VimPlugin.turnOnPlugin(VimPlugin.java:363)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by hadix-lin** [comment]
请更新到1.4.8版本，官方插件中心还在审核中。
可以下载自行安装 https://github.com/hadix-lin/ideavim_extension/releases/download/v1.4.8/ideavim_extension.zip
