### ISSUE TITLE
idea 2020.3 在apple silicon上报错

### ISSUE THREAD

**Issue by Sunmit** [hadix-lin/ideavim_extension#60]
idea 的 2020.3 apple silicon 测试版 目前使用插件报错
测试版下载地址
IntelliJ IDEA Ultimate 2020.3: https://download.jetbrains.com/idea/ideaIU-203.6494-aarch64.dmg
IntelliJ IDEA Community 2020.3: https://download.jetbrains.com/idea/ideaIC-203.6494-aarch64.dmg

错误信息如下：
java.lang.UnsatisfiedLinkError: Unable to load library 'input-source-switcher':
dlopen(libinput-source-switcher.dylib, 9): image not found
dlopen(libinput-source-switcher.dylib, 9): image not found
dlopen(/Users/Terry/Library/Frameworks/input-source-switcher.framework/input-source-switcher, 9): image not found
dlopen(/Library/Frameworks/input-source-switcher.framework/input-source-switcher, 9): image not found
dlopen(/System/Library/Frameworks/input-source-switcher.framework/input-source-switcher, 9): image not found
Native library (darwin-aarch64/libinput-source-switcher.dylib) not found in resource path (/Applications/IntelliJ IDEA.app/Contents/lib/bootstrap.jar:/Applications/IntelliJ IDEA.app/Contents/lib/extensions.jar:/Applications/IntelliJ IDEA.app/Contents/lib/util.jar:/Applications/IntelliJ IDEA.app/Contents/lib/jdom.jar:/Applications/IntelliJ IDEA.app/Contents/lib/log4j.jar:/Applications/IntelliJ IDEA.app/Contents/lib/jna.jar)
at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
at com.sun.jna.Native.register(Native.java:1722)
at com.sun.jna.Native.register(Native.java:1443)
at io.github.hadixlin.iss.mac.MacNative.<clinit>(MacNative.kt:9)
at io.github.hadixlin.iss.mac.MacInputMethodSwitcher.switchToEnglish(MacInputMethodSwitcher.kt:31)
at io.github.hadixlin.iss.SystemInputMethodSwitcher.switchToEnglish(SystemInputMethodSwitcher.kt:18)
at io.github.hadixlin.iss.InputMethodAutoSwitcher$focusListener$1$focusGained$1.run(InputMethodAutoSwitcher.kt:137)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libinput-source-switcher.dylib, 9): image not found
at com.sun.jna.Native.open(Native Method)
at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
... 10 more
Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libinput-source-switcher.dylib, 9): image not found
at com.sun.jna.Native.open(Native Method)
at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
... 10 more
Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/Terry/Library/Frameworks/input-source-switcher.framework/input-source-switcher, 9): image not found
at com.sun.jna.Native.open(Native Method)
at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
... 10 more
Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/input-source-switcher.framework/input-source-switcher, 9): image not found
at com.sun.jna.Native.open(Native Method)
at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
... 10 more
Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/input-source-switcher.framework/input-source-switcher, 9): image not found
at com.sun.jna.Native.open(Native Method)
at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
... 10 more
Suppressed: java.io.IOException: Native library (darwin-aarch64/libinput-source-switcher.dylib) not found in resource path (/Applications/IntelliJ IDEA.app/Contents/lib/bootstrap.jar:/Applications/IntelliJ IDEA.app/Contents/lib/extensions.jar:/Applications/IntelliJ IDEA.app/Contents/lib/util.jar:/Applications/IntelliJ IDEA.app/Contents/lib/jdom.jar:/Applications/IntelliJ IDEA.app/Contents/lib/log4j.jar:/Applications/IntelliJ IDEA.app/Contents/lib/jna.jar)
at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
... 10 more

**Comment by hadix-lin** [comment]
这个库需要针对silicon重新编译，但是我没有silicon笔记本，无法进行该工作，抱歉。

**Comment by amazingXiong** [comment]
我也遇到了类似的问题.....希望作者大大早日更新一下....感激不尽

**Comment by hadix-lin** [comment]
我也想解决这个问题，但没有m1没办法编译测试，待我借到m1，才能更新。
amazingXiong <notifications@github.com>于2021年1月16日 周六18:44写道：

**Comment by hadix-lin** [comment]
1.4.9 解决该问题，可以自行[下载安装](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.4.9/ideavim_extension.zip)，或等待插件中心更新。
