### ISSUE TITLE
IdeaVim 0.67 版本开始进入编辑模式无法恢复到之前的输入法了

### ISSUE THREAD

**Issue by hahaleyile** [hadix-lin/ideavim_extension#69]
今天刚刚升级了 IdeaVim，然后本来一切正常，现在按 ESC 退回到普通模式能切换到美式键盘，但再进入编辑模式就不会切换输入法了。
用的是微软默认的输入法。

**Comment by yahkun** [comment]
Same problem in macOS: keep english in normal but cannot restore in insert.

IdeaVim 0.67
IdeaVimExtension 1.4.9

**Comment by zhouqizi** [comment]
我也一样 
IdeaVim 0.67 
IdeaVimExtension 1.4.9

**Comment by hadix-lin** [comment]
[IdeaVimExtension.zip](https://github.com/hadix-lin/ideavim_extension/files/6550616/IdeaVimExtension.zip)
请大家下载安装这个包试试看

**Comment by hadix-lin** [comment]
> 我也一样
> IdeaVim 0.67
> IdeaVimExtension 1.4.9

可以帮我测试一下吗？

**Comment by zhouqizi** [comment]
> > 我也一样
> > IdeaVim 0.67
> > IdeaVimExtension 1.4.9Same for me, IDEAVIM 0.67 IdeaVim extension 1.4.9
> 
> 可以帮我测试一下吗？
> 
> Can you test it for me?

安装新包后,中英文切换可以使用, 但是出现了下列报错
![image](https://user-images.githubusercontent.com/42467308/119765442-e1cc8f80-bee5-11eb-90c3-8d9f5888b796.png)

**Comment by HideOnRose** [comment]
我也遇到了一样的问题

**Comment by zhouqizi** [comment]
出现下列报错后,IDEA创建类创建不了

**Comment by hadix-lin** [comment]
> > > 我也一样
> > > IdeaVim 0.67
> > > IdeaVimExtension 1.4.9Same for me, IDEAVIM 0.67 IdeaVim extension 1.4.9
> > 
> > 
> > 可以帮我测试一下吗？
> > Can you test it for me?
> 
> 安装新包后,中英文切换可以使用, 但是出现了下列报错
> ![image](https://user-images.githubusercontent.com/42467308/119765442-e1cc8f80-bee5-11eb-90c3-8d9f5888b796.png)

[IdeaVimExtension.zip](https://github.com/hadix-lin/ideavim_extension/files/6559064/IdeaVimExtension.zip)
请再试一下这个包，我尝试修正了一下。

**Comment by hahaleyile** [comment]
> > > > 我也一样
> > > > IdeaVim 0.67
> > > > IdeaVimExtension 1.4.9Same for me, IDEAVIM 0.67 IdeaVim extension 1.4.9
> > > 
> > > 
> > > 可以帮我测试一下吗？
> > > Can you test it for me?
> > 
> > 
> > 安装新包后,中英文切换可以使用, 但是出现了下列报错
> > ![image](https://user-images.githubusercontent.com/42467308/119765442-e1cc8f80-bee5-11eb-90c3-8d9f5888b796.png)
> 
> [IdeaVimExtension.zip](https://github.com/hadix-lin/ideavim_extension/files/6559064/IdeaVimExtension.zip)
> 请再试一下这个包，我尝试修正了一下。 @zhouqizi

您好，最新的包我在 Windows 平台下测试过了，中英文键盘切换没有问题，但还是有报错：

![image](https://user-images.githubusercontent.com/38727644/119956919-2afb0d00-bfd4-11eb-83f1-71bbe3632010.png)

`kotlin.TypeCastException: null cannot be cast to non-null type com.intellij.openapi.editor.Editor
	at io.github.hadixlin.iss.InputMethodAutoSwitcher$exitInsertModeListener$1.currentEditor(InputMethodAutoSwitcher.kt:75)
	at io.github.hadixlin.iss.InputMethodAutoSwitcher$exitInsertModeListener$1.commandFinished(InputMethodAutoSwitcher.kt:63)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:674)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:649)
	at com.intellij.util.messages.impl.MessageBusImpl.access$300(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.executeOrAddToQueue(MessageBusImpl.java:215)
	at com.intellij.util.messages.impl.CompositeMessageBus$ToDirectChildrenMessagePublisher.publish(CompositeMessageBus.java:113)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:181)
	at com.sun.proxy.$Proxy61.commandFinished(Unknown Source)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.fireCommandFinished(CoreCommandProcessor.java:275)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.finishCommand(CoreCommandProcessor.java:256)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.finishCommand(CommandProcessorImpl.java:34)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:222)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$projectOpened$27(FileEditorManagerImpl.java:1585)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by zhouqizi** [comment]
> > > > 我也一样
> > > > IdeaVim 0.67
> > > > IdeaVimExtension 1.4.9Same for me, IDEAVIM 0.67 IdeaVim extension 1.4.9
> > > 
> > > 
> > > 可以帮我测试一下吗？
> > > Can you test it for me?
> > 
> > 
> > 安装新包后,中英文切换可以使用, 但是出现了下列报错
> > ![image](https://user-images.githubusercontent.com/42467308/119765442-e1cc8f80-bee5-11eb-90c3-8d9f5888b796.png)
> 
> [IdeaVimExtension.zip](https://github.com/hadix-lin/ideavim_extension/files/6559064/IdeaVimExtension.zip)
> 请再试一下这个包，我尝试修正了一下。 @zhouqizi

环境
idea 版本 2020.3
ideavim 0.67
我下载新包测试后,出现下列报错
![image](https://user-images.githubusercontent.com/42467308/119970796-c0050280-bfe2-11eb-9edb-76122c330e9a.png)

**Comment by hadix-lin** [comment]
@zhouqizi 再帮忙测试一下这个包
[IdeaVimExtension.zip](https://github.com/hadix-lin/ideavim_extension/files/6568544/IdeaVimExtension.zip)

这次应该没啥问题了

**Comment by zhouqizi** [comment]
@hadix-lin 测试过了,没问题

**Comment by hadix-lin** [comment]
1.4.10 修正该问题，请遇到同样问题的用户[下载安装该版本](https://github.com/hadix-lin/ideavim_extension/releases/download/v1.4.10/IdeaVimExtension.zip)，谢谢。
