### ISSUE TITLE
启用时报错

### ISSUE THREAD

**Issue by alan-fu** [hadix-lin/ideavim_extension#7]
使用命令 `set keep-english-in-normal`报错

Error Message:
```
Could not initialize class io.github.hadixlin.iss.InputSourceSwitcher
```

Error Details
```
Could not initialize class io.github.hadixlin.iss.InputSourceSwitcher
java.lang.NoClassDefFoundError: Could not initialize class io.github.hadixlin.iss.InputSourceSwitcher
	at io.github.hadixlin.iss.SystemInputSource.getCurrentInputSource(SystemInputSource.java:22)
	at io.github.hadixlin.iss.KeepEnglishInNormalAndRestoreInInsertExtension$1.beforeCommandFinished(KeepEnglishInNormalAndRestoreInInsertExtension.java:74)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.fireCommandFinished(CoreCommandProcessor.java:203)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.finishCommand(CoreCommandProcessor.java:187)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.finishCommand(CommandProcessorImpl.java:54)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:155)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:107)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:86)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:570)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:619)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:618)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:633)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

软件版本信息
```
PhpStorm 2017.1.4
Build #PS-171.4694.2, built on May 16, 2017
Licensed to alan

JRE: 1.8.0_112-release-736-b21 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
Windows 10 10.0
```
插件版本

IdeaVim: 0.48
IdeaVimExtension: 1.1.3

**Comment by hadix-lin** [comment]
reademe里面有写,该插件仅支持macOS.抱歉.我不会写系统的本地代码,所以没能适配windows和linux.
