### ISSUE TITLE
webstorm 报错 了 , exception in plugin ideavimExtension 

### ISSUE THREAD

**Issue by ifnk** [hadix-lin/ideavim_extension#72]
`
java.lang.IllegalStateException: hwnd must not be null
	at io.github.hadixlin.iss.win.WinInputMethodSwitcher.switchToEnglish(WinInputMethodSwitcher.kt:41)
	at io.github.hadixlin.iss.SystemInputMethodSwitcher.switchToEnglish(SystemInputMethodSwitcher.kt:18)
	at io.github.hadixlin.iss.InputMethodAutoSwitcher$focusListener$1$focusGained$1.run(InputMethodAutoSwitcher.kt:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
`
用webstorm 的时候 报错 了  ，就报错了这一次，在 rider 上面 ，android studio 上面 是好用的 ，就 反馈下 …… 不影响使用

**Comment by hadix-lin** [comment]
谢谢，下个版本我处理一下windows这个null问题

**Comment by hadix-lin** [comment]
1.4.12修正该问题
